# Generated by Django 3.2.7 on 2022-04-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created', '-jadwal']},
        ),
        migrations.AlterModelOptions(
            name='organisasi',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='organisasi',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='org'),
        ),
    ]
