# Generated by Django 3.2.7 on 2022-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220407_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisasi',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='base/files/profilepic'),
        ),
    ]
