# Generated by Django 3.2.7 on 2022-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_organisasi_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lokasi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
