# Generated by Django 3.2.7 on 2022-04-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_event_jadwal'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisasi',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
