# Generated by Django 3.2.7 on 2022-04-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_organisasi_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='organisasi',
            name='showcase1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='organisasi',
            name='showcase2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='organisasi',
            name='showcase3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
