# Generated by Django 3.2.7 on 2022-04-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_feed_feedcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
