# Generated by Django 3.2.7 on 2022-04-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20220410_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisasi',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='organisasi',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='organisasi',
            name='showcase1',
            field=models.ImageField(blank=True, null=True, upload_to='showcase/'),
        ),
        migrations.AlterField(
            model_name='organisasi',
            name='showcase2',
            field=models.ImageField(blank=True, null=True, upload_to='showcase/'),
        ),
        migrations.AlterField(
            model_name='organisasi',
            name='showcase3',
            field=models.ImageField(blank=True, null=True, upload_to='showcase/'),
        ),
    ]
