# Generated by Django 3.2.7 on 2022-04-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='interest', to='base.Topic'),
        ),
    ]
