# Generated by Django 3.2.7 on 2022-04-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_event_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='organisasi',
            name='fakultas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.fakultas'),
        ),
    ]
