# Generated by Django 3.2.7 on 2022-04-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20220422_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fakultas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fakultas'),
        ),
    ]
