# Generated by Django 3.2.7 on 2022-04-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20220423_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fakultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fakultas'),
        ),
    ]
